/**
 * The disbursement API, as the browser sees it.
 *
 * Amounts are `minor` everywhere in these types — integers, never a decimal.
 * The names say so rather than leaving it to a comment, because a field called
 * `amount` is exactly the one somebody eventually divides by 100 in the wrong
 * place.
 */

import { apiFetch } from 'src/api/client';

export type TransferStatus = 'failed' | 'pending' | 'processing' | 'succeeded';

export interface Transfer {
  amountMinor: number;
  createdAt: string;
  currency: string;
  failureReason: null | string;
  id: string;
  providerReference: null | string;
  recipientId: string;
  recipientName: string;
  status: TransferStatus;
  updatedAt: string;
}

export type TaskStatus = 'cancelled' | 'failed' | 'pending' | 'running' | 'succeeded';

export interface Task {
  attempts: number;
  claimedBy: null | string;
  createdAt: string;
  error: null | string;
  id: string;
  kind: string;
  maxAttempts: number;
  runAt: string;
  status: TaskStatus;
  transferId: null | string;
  updatedAt: string;
}

export interface Line {
  accountId: string;
  accountKind: string;
  accountName: string;
  amountMinor: number;
  currency: string;
  direction: 'credit' | 'debit';
}

export interface Journal {
  createdAt: string;
  id: string;
  kind: string;
  lines: Line[];
  memo: null | string;
}

/** A transfer with its two histories: the books' account and the worker's. */
export interface TransferDetail extends Transfer {
  journals: Journal[];
  tasks: Task[];
}

export interface Recipient {
  country: string;
  enrolledAt: string;
  fullName: string;
  id: string;
  msisdn: string;
}

export interface Account {
  balanceMinor: number;
  currency: string;
  id: string;
  kind: string;
  name: string;
}

export interface Finding {
  createdAt: string;
  detail: string;
  healed: boolean;
  id: string;
  kind: string;
  providerReference: null | string;
  transferId: null | string;
}

export interface Overview {
  accounts: Account[];
  deadLettered: number;
  trialBalanceMinor: number;
  unresolvedFindings: number;
}

export interface DisburseRequest {
  amountMinor: number;
  currency: string;
  /**
   * Generated by the caller and **reused across retries of the same attempt**.
   * A fresh key per retry would defeat the entire point: the server would see
   * two unrelated requests and pay twice.
   */
  idempotencyKey: string;
  recipientId: string;
}

/**
 * Query keys, hierarchical so that invalidating a family reaches every
 * member: `['transfers']` covers the list and every `['transfers', id]`.
 */
export const ledgerKeys = {
  overview: ['overview'] as const,
  recipients: ['recipients'] as const,
  transfer: (id: string) => ['transfers', id] as const,
  transfers: ['transfers'] as const,
};

export function getOverview(): Promise<Overview> {
  return apiFetch<Overview>('/overview');
}

export function listTransfers(): Promise<Transfer[]> {
  return apiFetch<Transfer[]>('/transfers');
}

export function getTransfer(id: string): Promise<TransferDetail> {
  return apiFetch<TransferDetail>(`/transfers/${id}`);
}

export function listRecipients(): Promise<Recipient[]> {
  return apiFetch<Recipient[]>('/recipients');
}

export function listFindings(): Promise<Finding[]> {
  return apiFetch<Finding[]>('/findings');
}

export function disburse({
  amountMinor,
  currency,
  idempotencyKey,
  recipientId,
}: DisburseRequest): Promise<Transfer> {
  return apiFetch<Transfer>('/transfers', {
    body: JSON.stringify({ amountMinor, currency, recipientId }),
    headers: { 'Idempotency-Key': idempotencyKey },
    method: 'POST',
  });
}
