/**
 * The disbursement API, as the browser sees it.
 *
 * Amounts are `minor` everywhere in these types — integers, never a decimal.
 * The names say so rather than leaving it to a comment, because a field called
 * `amount` is exactly the one somebody eventually divides by 100 in the wrong
 * place.
 */

import { apiFetch } from 'src/api/client';

export type TransferStatus = 'failed' | 'pending' | 'processing' | 'succeeded';

export interface Transfer {
  amountMinor: number;
  createdAt: string;
  currency: string;
  failureReason: null | string;
  id: string;
  providerReference: null | string;
  recipientId: string;
  recipientName: string;
  /** The payment run this was authorised in, or null for a one-off. */
  runId: null | string;
  status: TransferStatus;
  updatedAt: string;
}

/**
 * A payment run with its progress. `byStatus` and `totalMinor` are counted
 * from the run's transfers on every read — a run has no status of its own to
 * disagree with them.
 */
export interface PaymentRun {
  byStatus: Partial<Record<TransferStatus, number>>;
  count: number;
  createdAt: string;
  currency: string;
  id: string;
  memo: null | string;
  totalMinor: number;
}

export interface RunRequest {
  currency: string;
  /** One per attempt, reused across retries. See `DisburseRequest`. */
  idempotencyKey: string;
  items: { amountMinor: number; recipientId: string }[];
  memo: null | string;
}

export type TaskStatus = 'cancelled' | 'failed' | 'pending' | 'running' | 'succeeded';

export interface Task {
  attempts: number;
  claimedBy: null | string;
  createdAt: string;
  error: null | string;
  id: string;
  kind: string;
  maxAttempts: number;
  runAt: string;
  status: TaskStatus;
  transferId: null | string;
  updatedAt: string;
}

export interface Line {
  accountId: string;
  accountKind: string;
  accountName: string;
  amountMinor: number;
  currency: string;
  direction: 'credit' | 'debit';
}

export interface Journal {
  createdAt: string;
  id: string;
  kind: string;
  lines: Line[];
  memo: null | string;
}

/**
 * The queue right now. `due` and `scheduled` are both pending work, split on
 * whether it may run yet — a settlement check a few seconds out is not a
 * backlog.
 */
export interface QueueSnapshot {
  active: Task[];
  dead: number;
  due: number;
  running: number;
  scheduled: number;
}

/** A transfer with its two histories: the books' account and the worker's. */
export interface TransferDetail extends Transfer {
  journals: Journal[];
  tasks: Task[];
}

export interface Recipient {
  country: string;
  enrolledAt: string;
  fullName: string;
  id: string;
  msisdn: string;
}

export interface Account {
  balanceMinor: number;
  currency: string;
  id: string;
  kind: string;
  name: string;
}

export interface Finding {
  createdAt: string;
  detail: string;
  healed: boolean;
  id: string;
  kind: string;
  providerReference: null | string;
  transferId: null | string;
}

export interface Overview {
  accounts: Account[];
  deadLettered: number;
  trialBalanceMinor: number;
  unresolvedFindings: number;
}

export interface DisburseRequest {
  amountMinor: number;
  currency: string;
  /**
   * Generated by the caller and **reused across retries of the same attempt**.
   * A fresh key per retry would defeat the entire point: the server would see
   * two unrelated requests and pay twice.
   */
  idempotencyKey: string;
  recipientId: string;
}

/**
 * Query keys, hierarchical so that invalidating a family reaches every
 * member: `['transfers']` covers the list and every `['transfers', id]`.
 */
export const ledgerKeys = {
  /** Under `tasks`, so every task notice reaches it. */
  deadLetters: ['tasks', 'dead'] as const,
  findings: ['findings'] as const,
  overview: ['overview'] as const,
  /** Under `tasks`, so every task notice reaches it. */
  queue: ['tasks', 'queue'] as const,
  recipients: ['recipients'] as const,
  runs: ['runs'] as const,
  tasks: ['tasks'] as const,
  transfer: (id: string) => ['transfers', id] as const,
  transfers: ['transfers'] as const,
  /** Under `transfers`, so a change to any transfer reaches the filtered list too. */
  transfersInRun: (runId: string) => ['transfers', 'run', runId] as const,
};

export function getOverview(): Promise<Overview> {
  return apiFetch<Overview>('/overview');
}

export function listTransfers(runId?: null | string): Promise<Transfer[]> {
  const query = runId ? `?run_id=${encodeURIComponent(runId)}` : '';
  return apiFetch<Transfer[]>(`/transfers${query}`);
}

export function listRuns(): Promise<PaymentRun[]> {
  return apiFetch<PaymentRun[]>('/runs');
}

export function createRun({
  currency,
  idempotencyKey,
  items,
  memo,
}: RunRequest): Promise<PaymentRun> {
  return apiFetch<PaymentRun>('/runs', {
    body: JSON.stringify({ currency, items, memo }),
    headers: { 'Idempotency-Key': idempotencyKey },
    method: 'POST',
  });
}

export function getTransfer(id: string): Promise<TransferDetail> {
  return apiFetch<TransferDetail>(`/transfers/${id}`);
}

export function listRecipients(): Promise<Recipient[]> {
  return apiFetch<Recipient[]>('/recipients');
}

export function listFindings(): Promise<Finding[]> {
  return apiFetch<Finding[]>('/findings');
}

export function disburse({
  amountMinor,
  currency,
  idempotencyKey,
  recipientId,
}: DisburseRequest): Promise<Transfer> {
  return apiFetch<Transfer>('/transfers', {
    body: JSON.stringify({ amountMinor, currency, recipientId }),
    headers: { 'Idempotency-Key': idempotencyKey },
    method: 'POST',
  });
}

export function getQueue(): Promise<QueueSnapshot> {
  return apiFetch<QueueSnapshot>('/queue');
}

export function listDeadLetters(): Promise<Task[]> {
  return apiFetch<Task[]>('/dead-letters');
}

/**
 * Put a dead-lettered task back on the queue. No idempotency key: the server
 * refuses a task that is no longer dead, so a repeat is refused, not doubled.
 */
export function retryDeadLetter(taskId: string): Promise<Task> {
  return apiFetch<Task>(`/dead-letters/${taskId}/retry`, { method: 'POST' });
}
