"""one system account per currency

Revision ID: 8660dde5af3f
Revises: 844b122b3fc5
Create Date: 2026-09-19 01:10:14.973504+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8660dde5af3f'
down_revision: str | None = '844b122b3fc5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('accounts_system_kind_currency_idx', 'accounts', ['kind', 'currency'], unique=True, postgresql_where=sa.text('recipient_id is null'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('accounts_system_kind_currency_idx', table_name='accounts', postgresql_where=sa.text('recipient_id is null'))
    # ### end Alembic commands ###
