"""tasks transfer index

Revision ID: 0f25e4a297ba
Revises: b819d579465b
Create Date: 2026-09-21 20:12:39.211816+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0f25e4a297ba'
down_revision: str | None = 'b819d579465b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tasks_transfer_idx', 'tasks', [sa.literal_column("(payload ->> 'transfer_id')")], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tasks_transfer_idx', table_name='tasks')
    # ### end Alembic commands ###
