"""provider payments

Revision ID: 844b122b3fc5
Revises: b00a323c3038
Create Date: 2026-09-19 01:00:35.731232+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '844b122b3fc5'
down_revision: str | None = 'b00a323c3038'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_payments',
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('msisdn', sa.Text(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending', 'succeeded', 'failed')", name='provider_payments_status_check'),
    sa.CheckConstraint('amount_minor > 0', name='provider_payments_amount_check'),
    sa.PrimaryKeyConstraint('reference'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('provider_payments_created_idx', 'provider_payments', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('provider_payments_created_idx', table_name='provider_payments')
    op.drop_table('provider_payments')
    # ### end Alembic commands ###
