"""ledger schema

Revision ID: b00a323c3038
Revises: 0001_initial
Create Date: 2026-09-19 00:52:28.584549+00:00

The tables are autogenerated. **The two triggers at the bottom are not, and
never will be** — Alembic diffs tables, indexes and constraints, and has no
idea a trigger exists. Delete one by hand and no future `--autogenerate` will
tell you it is missing; the books will simply stop being checked.

They are the two rules that make this a ledger rather than a table of numbers:

  1. every journal entry balances, and
  2. nothing ever changes a line once it is written.

Both live here rather than in Python because the application is not the only
thing that can write to this database. A psql session, a data fix, a future
service in another language, or a bug in our own service all bypass an
application-level check. None of them bypass this.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = "b00a323c3038"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipients",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("msisdn", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column(
            "enrolled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("msisdn ~ '^\\+[1-9][0-9]{6,14}$'", name="recipients_msisdn_check"),
        sa.CheckConstraint("char_length(country) = 2", name="recipients_country_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("msisdn"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'recipient_payable') = (recipient_id is not null)",
            name="accounts_recipient_kind_check",
        ),
        sa.CheckConstraint(
            "kind in ('program_funding', 'recipient_payable', 'provider_settlement')",
            name="accounts_kind_check",
        ),
        sa.CheckConstraint("char_length(currency) = 3", name="accounts_currency_check"),
        sa.ForeignKeyConstraint(["recipient_id"], ["recipients.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "accounts_recipient_currency_idx",
        "accounts",
        ["recipient_id", "currency"],
        unique=True,
        postgresql_where=sa.text("recipient_id is not null"),
    )
    op.create_table(
        "transfers",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("provider_reference", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('pending', 'processing', 'succeeded', 'failed')",
            name="transfers_status_check",
        ),
        sa.CheckConstraint("amount_minor > 0", name="transfers_amount_check"),
        sa.CheckConstraint("char_length(currency) = 3", name="transfers_currency_check"),
        sa.ForeignKeyConstraint(["recipient_id"], ["recipients.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_reference"),
    )
    op.create_index(
        "transfers_recipient_idx",
        "transfers",
        ["recipient_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "transfers_status_idx",
        "transfers",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("request_fingerprint", sa.Text(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("transfer_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["transfer_id"], ["transfers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("key"),
        sa.UniqueConstraint("key", "endpoint", name="idempotency_keys_key_endpoint_key"),
    )
    op.create_index(
        "idempotency_keys_created_idx",
        "idempotency_keys",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("transfer_id", sa.UUID(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind in ('funding_deposit', 'transfer_authorized', 'transfer_settled', 'transfer_reversed')",
            name="journal_entries_kind_check",
        ),
        sa.ForeignKeyConstraint(["transfer_id"], ["transfers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "journal_entries_transfer_idx", "journal_entries", ["transfer_id"], unique=False
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("journal_entry_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction in ('debit', 'credit')", name="ledger_entries_direction_check"
        ),
        sa.CheckConstraint("amount_minor > 0", name="ledger_entries_amount_check"),
        sa.CheckConstraint("char_length(currency) = 3", name="ledger_entries_currency_check"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["journal_entry_id"], ["journal_entries.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ledger_entries_account_idx",
        "ledger_entries",
        ["account_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ledger_entries_journal_idx", "ledger_entries", ["journal_entry_id"], unique=False
    )
    # ### end Alembic commands ###

    # ------------------------------------------------- the balance invariant
    #
    # DEFERRABLE INITIALLY DEFERRED is the entire trick, and it is not an
    # optimisation. A journal's lines are inserted one row at a time, so the
    # journal is unbalanced between the first INSERT and the last: an immediate
    # check would reject every correct posting ever made. COMMIT is the first
    # moment at which "does this journal balance" is a well-formed question.
    #
    # A CONSTRAINT TRIGGER, not an ordinary one, because only a constraint
    # trigger can be deferred.
    #
    # FOR EACH ROW rather than a statement trigger: a statement trigger cannot
    # be deferred per row, and multi-row inserts would check once for the whole
    # statement rather than once per journal touched. The repeated work on a
    # two-line journal is two identical aggregate queries, which is cheap and
    # correct; a rollup would be neither.
    op.execute("""
        create or replace function assert_journal_balances() returns trigger
        language plpgsql as $$
        declare
            imbalance bigint;
            line_count int;
            currency_count int;
        begin
            select
                coalesce(sum(case when direction = 'debit' then amount_minor
                                  else -amount_minor end), 0),
                count(*),
                count(distinct currency)
              into imbalance, line_count, currency_count
              from ledger_entries
             where journal_entry_id = new.journal_entry_id;

            -- Zero lines means the journal's rows were deleted out from under
            -- it, which the append-only trigger below already refuses. Nothing
            -- to check, and erroring here would only obscure that message.
            if line_count = 0 then
                return null;
            end if;

            if line_count < 2 then
                raise exception
                    'journal entry % has % line(s); a posting moves money between at least two accounts',
                    new.journal_entry_id, line_count
                    using errcode = 'check_violation';
            end if;

            -- One journal may not straddle two currencies. Summing minor units
            -- across them would "balance" 100 KES against 100 USD, which is
            -- the most expensive kind of bug this table can have. Cross-
            -- currency movement is two journals and an explicit FX leg.
            if currency_count > 1 then
                raise exception
                    'journal entry % mixes % currencies; post an explicit FX leg instead',
                    new.journal_entry_id, currency_count
                    using errcode = 'check_violation';
            end if;

            if imbalance <> 0 then
                raise exception
                    'journal entry % does not balance: debits minus credits = %',
                    new.journal_entry_id, imbalance
                    using errcode = 'check_violation';
            end if;

            return null;
        end;
        $$;
    """)
    op.execute("""
        create constraint trigger ledger_entries_balance
        after insert on ledger_entries
        deferrable initially deferred
        for each row execute function assert_journal_balances();
    """)

    # ----------------------------------------------------------- append-only
    #
    # A mistake is corrected by posting a reversing journal entry, which leaves
    # both the error and the correction in the history. That is the whole point
    # of keeping books this way, and an UPDATE would leave neither.
    #
    # Not deferred: unlike the balance rule, this one is well-formed the
    # instant it is violated, and failing at the offending statement points at
    # the line that did it rather than at COMMIT.
    op.execute("""
        create or replace function refuse_ledger_mutation() returns trigger
        language plpgsql as $$
        begin
            raise exception
                'ledger_entries is append-only (attempted % on entry %)',
                tg_op, old.id
                using errcode = 'check_violation',
                      hint = 'Post a reversing journal entry instead.';
        end;
        $$;
    """)
    op.execute("""
        create trigger ledger_entries_append_only
        before update or delete on ledger_entries
        for each row execute function refuse_ledger_mutation();
    """)


def downgrade() -> None:
    # Triggers first: dropping ledger_entries with the append-only trigger
    # still attached does not fail, but leaving the functions behind after the
    # tables are gone does leave a broken re-upgrade.
    op.execute("drop trigger if exists ledger_entries_append_only on ledger_entries")
    op.execute("drop trigger if exists ledger_entries_balance on ledger_entries")
    op.execute("drop function if exists refuse_ledger_mutation()")
    op.execute("drop function if exists assert_journal_balances()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ledger_entries_journal_idx", table_name="ledger_entries")
    op.drop_index("ledger_entries_account_idx", table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index("journal_entries_transfer_idx", table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index("idempotency_keys_created_idx", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("transfers_status_idx", table_name="transfers")
    op.drop_index("transfers_recipient_idx", table_name="transfers")
    op.drop_table("transfers")
    op.drop_index(
        "accounts_recipient_currency_idx",
        table_name="accounts",
        postgresql_where=sa.text("recipient_id is not null"),
    )
    op.drop_table("accounts")
    op.drop_table("recipients")
    # ### end Alembic commands ###
