"""reconciliation findings

Revision ID: b819d579465b
Revises: 8660dde5af3f
Create Date: 2026-09-19 01:24:38.350823+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b819d579465b'
down_revision: str | None = '8660dde5af3f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('provider_reference', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('healed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('missing_at_provider', 'unknown_to_us', 'status_behind', 'status_contradicted', 'amount_mismatch')", name='reconciliation_findings_kind_check'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('reconciliation_findings_created_idx', 'reconciliation_findings', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('reconciliation_findings_created_idx', table_name='reconciliation_findings')
    op.drop_table('reconciliation_findings')
    # ### end Alembic commands ###
