"""payment runs

Read before committing, and one thing changed: autogenerate emitted the new
foreign key with no name, which `upgrade` survives (Postgres picks one) and
`downgrade` does not (it cannot drop a constraint it cannot name). Named in
the model as well, so the next autogenerate agrees with this one.

Revision ID: 632b14bca5a4
Revises: 0f25e4a297ba
Create Date: 2026-09-23 20:50:41.052865+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '632b14bca5a4'
down_revision: str | None = '0f25e4a297ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name='payment_runs_currency_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('payment_runs_created_idx', 'payment_runs', [sa.literal_column('created_at DESC')], unique=False)
    op.add_column('transfers', sa.Column('run_id', sa.UUID(), nullable=True))
    op.create_index('transfers_run_idx', 'transfers', ['run_id'], unique=False)
    op.create_foreign_key('transfers_run_id_fkey', 'transfers', 'payment_runs', ['run_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transfers_run_id_fkey', 'transfers', type_='foreignkey')
    op.drop_index('transfers_run_idx', table_name='transfers')
    op.drop_column('transfers', 'run_id')
    op.drop_index('payment_runs_created_idx', table_name='payment_runs')
    op.drop_table('payment_runs')
    # ### end Alembic commands ###
