"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-18 19:40:00.000000+00:00

Hand-written rather than autogenerated, and squashed to one revision. The three
revisions this replaces were the chat template's history — they built tables
this project does not have, and carrying them would mean every fresh database
created and then dropped a schema nobody here uses. There is no deployed
database with those revisions applied, which is the only thing that makes
squashing safe. It will not be safe again.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Alembic diffs tables, not extensions, so this is the kind of thing you
    # only ever get by reading the revision. Postgres 13+ has gen_random_uuid()
    # in core and does not need pgcrypto, but the column default below names
    # that function, and this makes the dependency explicit rather than a
    # property of whichever server version someone happens to run.
    op.execute('create extension if not exists "pgcrypto"')

    op.create_table(
        "tasks",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "cancel_requested", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('pending', 'running', 'succeeded', 'failed', 'cancelled')",
            name="tasks_status_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "tasks_claim_idx",
        "tasks",
        ["run_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "tasks_kind_idx", "tasks", ["kind", sa.literal_column("created_at DESC")], unique=False
    )


def downgrade() -> None:
    op.drop_index("tasks_kind_idx", table_name="tasks")
    op.drop_index(
        "tasks_claim_idx", table_name="tasks", postgresql_where=sa.text("status = 'pending'")
    )
    op.drop_table("tasks")
