"""drop task cancellation

Nothing ever requested a cancellation or set a task `cancelled`, so the column
and the status go. Autogenerate emitted the column and, as ever, not the CHECK
constraint, which is rewritten by hand below.

Revision ID: a637f2d88599
Revises: 632b14bca5a4
Create Date: 2026-09-23 23:40:31.184957+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a637f2d88599'
down_revision: str | None = '632b14bca5a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'cancel_requested')
    # ### end Alembic commands ###

    op.drop_constraint('tasks_status_check', 'tasks', type_='check')
    op.create_check_constraint(
        'tasks_status_check', 'tasks', "status in ('pending', 'running', 'succeeded', 'failed')"
    )


def downgrade() -> None:
    op.drop_constraint('tasks_status_check', 'tasks', type_='check')
    op.create_check_constraint(
        'tasks_status_check',
        'tasks',
        "status in ('pending', 'running', 'succeeded', 'failed', 'cancelled')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('cancel_requested', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
